package isimarket.servants.walletservant;


/**
* isimarket/model/servants/walletservant/WalletServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* jeudi 17 avril 2008 23 h 11 CEST
*/

public interface WalletServantOperations 
{
  isimarket.model.Wallet getWallet (String operatorLogin, String password);
  isimarket.model.Action[] getActionList (int walletId);
  isimarket.model.Action getAction (int actionId);
  int buyAction (int walletId, String actionTypeCode, int quantity) throws isimarket.servants.walletservant.WalletServantPackage.BadQuantityException;
  void sellAction (int walletActionId, String actionTypeCode, int actionId, int quantity);
} // interface WalletServantOperations
