package isimarket.servants.walletservant;


/**
* isimarket/model/servants/walletservant/WalletServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* vendredi 18 avril 2008 00 h 18 CEST
*/

public interface WalletServantOperations 
{
  isimarket.model.Wallet authentication (String operatorLogin, String password);
  isimarket.model.Action[] getActionList (int walletId);
  isimarket.model.Action getAction (int actionId);
  isimarket.model.Action buyAction (int walletId, String actionTypeCode, int quantity) throws isimarket.servants.walletservant.WalletServantPackage.BadQuantityException, isimarket.servants.walletservant.WalletServantPackage.NotEnoughCashException;
  void sellAction (int walletId, String actionTypeCode, int actionId, int quantity);
} // interface WalletServantOperations
