package isimarket.servants.walletservant;


/**
* isimarket/model/servants/walletservant/WalletServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* vendredi 18 avril 2008 00 h 18 CEST
*/

public interface WalletServant extends WalletServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WalletServant
