package isimarket.servants.alarmservant;


/**
* isimarket/model/servants/alarmservant/_AlarmServantStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* samedi 29 mars 2008 11 h 45 CET
*/

public class _AlarmServantStub extends org.omg.CORBA.portable.ObjectImpl implements isimarket.servants.alarmservant.AlarmServant
{

  public isimarket.model.AlarmType[] getAlarmTypeList ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAlarmTypeList", true);
                $in = _invoke ($out);
                isimarket.model.AlarmType $result[] = isimarket.model.AlarmTypeListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAlarmTypeList (        );
            } finally {
                _releaseReply ($in);
            }
  } // getAlarmTypeList

  public isimarket.model.AlarmType getAlarmType (int alarmTypeId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAlarmType", true);
                $out.write_long (alarmTypeId);
                $in = _invoke ($out);
                isimarket.model.AlarmType $result = isimarket.model.AlarmTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAlarmType (alarmTypeId        );
            } finally {
                _releaseReply ($in);
            }
  } // getAlarmType

  public void createAlarmType (int alarmTypeId, String label)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createAlarmType", true);
                $out.write_long (alarmTypeId);
                $out.write_string (label);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                createAlarmType (alarmTypeId, label        );
            } finally {
                _releaseReply ($in);
            }
  } // createAlarmType

  public void deleteAlarmType (int alarmTypeId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deleteAlarmType", true);
                $out.write_long (alarmTypeId);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                deleteAlarmType (alarmTypeId        );
            } finally {
                _releaseReply ($in);
            }
  } // deleteAlarmType

  public void createAlarm (int alarmType_id, String actionTypeCode)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createAlarm", true);
                $out.write_long (alarmType_id);
                $out.write_string (actionTypeCode);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                createAlarm (alarmType_id, actionTypeCode        );
            } finally {
                _releaseReply ($in);
            }
  } // createAlarm

  public void deleteAlarm (int alarmType_id, String actionTypeCode)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deleteAlarm", true);
                $out.write_long (alarmType_id);
                $out.write_string (actionTypeCode);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                deleteAlarm (alarmType_id, actionTypeCode        );
            } finally {
                _releaseReply ($in);
            }
  } // deleteAlarm

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:isimarket/model/servants/alarmservant/AlarmServant:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _AlarmServantStub
