package isimarket.servants.alarmservant;


/**
* isimarket/model/servants/alarmservant/AlarmServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 13 mai 2008 19 h 01 CEST
*/

public interface AlarmServant extends AlarmServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AlarmServant
