package isimarket.servants.alarmservant;


/**
* isimarket/model/servants/alarmservant/AlarmServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 25 mars 2008 18 h 20 CET
*/

public interface AlarmServantOperations 
{
} // interface AlarmServantOperations
