package isimarket.servants.alarmservant;


/**
* isimarket/model/servants/alarmservant/AlarmServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 24 mars 2008 12 h 24 CET
*/

public interface AlarmServant extends AlarmServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AlarmServant
