package isimarket.servants.alarmservant;

/**
* isimarket/model/servants/alarmservant/AlarmServantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 24 mars 2008 12 h 24 CET
*/

public final class AlarmServantHolder implements org.omg.CORBA.portable.Streamable
{
  public isimarket.servants.alarmservant.AlarmServant value = null;

  public AlarmServantHolder ()
  {
  }

  public AlarmServantHolder (isimarket.servants.alarmservant.AlarmServant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isimarket.servants.alarmservant.AlarmServantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isimarket.servants.alarmservant.AlarmServantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isimarket.servants.alarmservant.AlarmServantHelper.type ();
  }

}
