package isimarket.servants.alarmservant;


/**
* isimarket/model/servants/alarmservant/AlarmServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 21 avril 2008 11 h 15 CEST
*/

public interface AlarmServant extends AlarmServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AlarmServant
