package isimarket.model;

/**
* isimarket/model/ActionTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* mardi 25 mars 2008 18 h 50 CET
*/

public final class ActionTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public isimarket.model.ActionType value = null;

  public ActionTypeHolder ()
  {
  }

  public ActionTypeHolder (isimarket.model.ActionType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isimarket.model.ActionTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isimarket.model.ActionTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isimarket.model.ActionTypeHelper.type ();
  }

}
