package isimarket.model;


/**
* isimarket/model/ActionType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 18 mai 2008 17 h 48 CEST
*/

public final class ActionType implements org.omg.CORBA.portable.IDLEntity
{
  public String code = null;
  public String label = null;
  public String introductionDate = null;
  public float introductionPrice = (float)0;
  public int quantity = (int)0;
  public float currentPrice = (float)0;

  public ActionType ()
  {
  } // ctor

  public ActionType (String _code, String _label, String _introductionDate, float _introductionPrice, int _quantity, float _currentPrice)
  {
    code = _code;
    label = _label;
    introductionDate = _introductionDate;
    introductionPrice = _introductionPrice;
    quantity = _quantity;
    currentPrice = _currentPrice;
  } // ctor

} // class ActionType
