package isimarket.model;


/**
* isimarket/model/Action.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* lundi 24 mars 2008 11 h 43 CET
*/

public final class Action implements org.omg.CORBA.portable.IDLEntity
{
  public int action_id = (int)0;
  public float buyPrice = (float)0;
  public String buyDate = null;

  //Wallet wallet;
  public isimarket.model.ActionType actiontype = null;

  public Action ()
  {
  } // ctor

  public Action (int _action_id, float _buyPrice, String _buyDate, isimarket.model.ActionType _actiontype)
  {
    action_id = _action_id;
    buyPrice = _buyPrice;
    buyDate = _buyDate;
    actiontype = _actiontype;
  } // ctor

} // class Action
