package isimarket.model;


/**
* isimarket/model/Administrator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 18 mai 2008 17 h 48 CEST
*/

public final class Administrator implements org.omg.CORBA.portable.IDLEntity
{
  public String login = null;
  public String password = null;

  public Administrator ()
  {
  } // ctor

  public Administrator (String _login, String _password)
  {
    login = _login;
    password = _password;
  } // ctor

} // class Administrator
