package isimarket.model;


/**
* isimarket/model/AlarmType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 18 mai 2008 17 h 48 CEST
*/

public final class AlarmType implements org.omg.CORBA.portable.IDLEntity
{
  public int alarmTypeId = (int)0;
  public String label = null;
  public String symbol = null;
  public float value = (float)0;

  public AlarmType ()
  {
  } // ctor

  public AlarmType (int _alarmTypeId, String _label, String _symbol, float _value)
  {
    alarmTypeId = _alarmTypeId;
    label = _label;
    symbol = _symbol;
    value = _value;
  } // ctor

} // class AlarmType
