package isimarket.model;


/**
* isimarket/model/AlarmType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* mardi 13 mai 2008 18 h 55 CEST
*/

public final class AlarmType implements org.omg.CORBA.portable.IDLEntity
{
  public int alarmTypeId = (int)0;
  public String label = null;
  public String symbol = null;

  public AlarmType ()
  {
  } // ctor

  public AlarmType (int _alarmTypeId, String _label, String _symbol)
  {
    alarmTypeId = _alarmTypeId;
    label = _label;
    symbol = _symbol;
  } // ctor

} // class AlarmType
