package isimarket.model;


/**
* isimarket/model/EventListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 18 mai 2008 17 h 48 CEST
*/

public final class EventListHolder implements org.omg.CORBA.portable.Streamable
{
  public isimarket.model.Event value[] = null;

  public EventListHolder ()
  {
  }

  public EventListHolder (isimarket.model.Event[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isimarket.model.EventListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isimarket.model.EventListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isimarket.model.EventListHelper.type ();
  }

}
