package isimarket.model;

/**
* isimarket/model/EventHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* mardi 8 avril 2008 19 h 22 CEST
*/

public final class EventHolder implements org.omg.CORBA.portable.Streamable
{
  public isimarket.model.Event value = null;

  public EventHolder ()
  {
  }

  public EventHolder (isimarket.model.Event initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isimarket.model.EventHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isimarket.model.EventHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isimarket.model.EventHelper.type ();
  }

}
