package isimarket.model;


/**
* isimarket/model/Operator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* samedi 29 mars 2008 11 h 45 CET
*/

public final class Operator implements org.omg.CORBA.portable.IDLEntity
{
  public String login = null;
  public String password = null;
  public isimarket.model.Wallet wallet = null;

  public Operator ()
  {
  } // ctor

  public Operator (String _login, String _password, isimarket.model.Wallet _wallet)
  {
    login = _login;
    password = _password;
    wallet = _wallet;
  } // ctor

} // class Operator
