package isimarket.servants.actiontypeservant;


/**
* isimarket/model/servants/actiontypeservant/ActionTypeServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* vendredi 18 avril 2008 00 h 18 CEST
*/

public interface ActionTypeServant extends ActionTypeServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ActionTypeServant
