package isimarket.servants.actiontypeservant;


/**
* isimarket/model/servants/actiontypeservant/ActionTypeServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* samedi 19 avril 2008 19 h 16 CEST
*/

public interface ActionTypeServant extends ActionTypeServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ActionTypeServant
