package isimarket.servants.actiontypeservant;


/**
* isimarket/model/servants/actiontypeservant/ActionTypeServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 12 mai 2008 16 h 16 CEST
*/

public interface ActionTypeServantOperations 
{
  isimarket.model.ActionType[] getActionTypeList ();
  isimarket.model.ActionType getActionType (String actionTypeCode);
  isimarket.model.ActionType getLastInsertedActionType ();
  void createActionType (String code, String label, String introductionDate, float introductionPrice, int quantity, float currentPrice);
  void updateActionTypeQuantity (String code, int quantity);
  void updateActionTypeCurrentPrice (String code, float currentPrice);
  void deleteActionType (String actionTypeCode);
} // interface ActionTypeServantOperations
