package isimarket.servants.actiontypeservant;


/**
* isimarket/model/servants/actiontypeservant/ActionTypeServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* dimanche 30 mars 2008 15 h 51 CEST
*/

public interface ActionTypeServantOperations 
{
  isimarket.model.ActionType[] getActionTypeList ();
  isimarket.model.ActionType getActionType (String actionTypeCode);
  void createNewActionType (isimarket.model.ActionType newActionType);
  void updateActionType (float newPrice);
} // interface ActionTypeServantOperations
