package isimarket.servants.eventservant;


/**
* isimarket/model/servants/eventservant/EventServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 21 avril 2008 12 h 28 CEST
*/

public interface EventServant extends EventServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EventServant
