package isimarket.servants.actionservant;


/**
* isimarket/model/servants/actionservant/ActionServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 25 mars 2008 18 h 20 CET
*/

public interface ActionServant extends ActionServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ActionServant
