package isimarket.servants.actionservant;


/**
* isimarket/model/servants/actionservant/ActionServantHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 25 mars 2008 18 h 20 CET
*/

abstract public class ActionServantHelper
{
  private static String  _id = "IDL:isimarket/model/servants/actionservant/ActionServant:1.0";

  public static void insert (org.omg.CORBA.Any a, isimarket.servants.actionservant.ActionServant that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static isimarket.servants.actionservant.ActionServant extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (isimarket.servants.actionservant.ActionServantHelper.id (), "ActionServant");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static isimarket.servants.actionservant.ActionServant read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ActionServantStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, isimarket.servants.actionservant.ActionServant value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static isimarket.servants.actionservant.ActionServant narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof isimarket.servants.actionservant.ActionServant)
      return (isimarket.servants.actionservant.ActionServant)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      isimarket.servants.actionservant._ActionServantStub stub = new isimarket.servants.actionservant._ActionServantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static isimarket.servants.actionservant.ActionServant unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof isimarket.servants.actionservant.ActionServant)
      return (isimarket.servants.actionservant.ActionServant)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      isimarket.servants.actionservant._ActionServantStub stub = new isimarket.servants.actionservant._ActionServantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
