package isimarket.servants.actionservant;

/**
* isimarket/model/servants/actionservant/ActionServantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* samedi 29 mars 2008 11 h 45 CET
*/

public final class ActionServantHolder implements org.omg.CORBA.portable.Streamable
{
  public isimarket.servants.actionservant.ActionServant value = null;

  public ActionServantHolder ()
  {
  }

  public ActionServantHolder (isimarket.servants.actionservant.ActionServant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isimarket.servants.actionservant.ActionServantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isimarket.servants.actionservant.ActionServantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isimarket.servants.actionservant.ActionServantHelper.type ();
  }

}
