package isimarket.servants.actionservant;


/**
* isimarket/model/servants/actionservant/ActionServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* samedi 29 mars 2008 11 h 45 CET
*/

public interface ActionServantOperations 
{
  isimarket.model.ActionType[] getActionTypeList ();
  isimarket.model.ActionType getActionType (String actionTypeCode);
} // interface ActionServantOperations
