package isimarket.servants.webservant;


/**
* isimarket/model/servants/webservant/_WebServantImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 24 mars 2008 12 h 24 CET
*/

public abstract class _WebServantImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements isimarket.servants.webservant.WebServant, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _WebServantImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createNewActionType", new java.lang.Integer (0));
    _methods.put ("updateActionType", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // isimarket/model/servants/webservant/WebServant/createNewActionType
       {
         isimarket.model.ActionType newAcionType = isimarket.model.ActionTypeHelper.read (in);
         this.createNewActionType (newAcionType);
         out = $rh.createReply();
         break;
       }

       case 1:  // isimarket/model/servants/webservant/WebServant/updateActionType
       {
         float newPrice = in.read_float ();
         this.updateActionType (newPrice);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:isimarket/model/servants/webservant/WebServant:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _WebServantImplBase
