package isimarket.servants.webservant;


/**
* isimarket/model/servants/webservant/WebServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* samedi 29 mars 2008 11 h 45 CET
*/

public interface WebServantOperations 
{
  void createNewActionType (isimarket.model.ActionType newActionType);
  void updateActionType (float newPrice);
} // interface WebServantOperations
