package isimarket.servants.webservant;


/**
* isimarket/model/servants/webservant/WebServantHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* samedi 29 mars 2008 11 h 45 CET
*/

abstract public class WebServantHelper
{
  private static String  _id = "IDL:isimarket/model/servants/webservant/WebServant:1.0";

  public static void insert (org.omg.CORBA.Any a, isimarket.servants.webservant.WebServant that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static isimarket.servants.webservant.WebServant extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (isimarket.servants.webservant.WebServantHelper.id (), "WebServant");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static isimarket.servants.webservant.WebServant read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_WebServantStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, isimarket.servants.webservant.WebServant value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static isimarket.servants.webservant.WebServant narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof isimarket.servants.webservant.WebServant)
      return (isimarket.servants.webservant.WebServant)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      isimarket.servants.webservant._WebServantStub stub = new isimarket.servants.webservant._WebServantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static isimarket.servants.webservant.WebServant unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof isimarket.servants.webservant.WebServant)
      return (isimarket.servants.webservant.WebServant)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      isimarket.servants.webservant._WebServantStub stub = new isimarket.servants.webservant._WebServantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
