package isimarket.model;

/**
* isimarket/model/WalletActionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 30 mars 2008 16 h 50 CEST
*/

public final class WalletActionHolder implements org.omg.CORBA.portable.Streamable
{
  public isimarket.model.WalletAction value = null;

  public WalletActionHolder ()
  {
  }

  public WalletActionHolder (isimarket.model.WalletAction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isimarket.model.WalletActionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isimarket.model.WalletActionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isimarket.model.WalletActionHelper.type ();
  }

}
