package isimarket.model;


/**
* isimarket/model/WalletActionListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 30 mars 2008 16 h 50 CEST
*/

public final class WalletActionListHolder implements org.omg.CORBA.portable.Streamable
{
  public isimarket.model.WalletAction value[] = null;

  public WalletActionListHolder ()
  {
  }

  public WalletActionListHolder (isimarket.model.WalletAction[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isimarket.model.WalletActionListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isimarket.model.WalletActionListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isimarket.model.WalletActionListHelper.type ();
  }

}
