package isimarket.servants.administrationservant;


/**
* isimarket/model/servants/administrationservant/_AdministrationServantImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 8 avril 2008 19 h 27 CEST
*/

public abstract class _AdministrationServantImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements isimarket.servants.administrationservant.AdministrationServant, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _AdministrationServantImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("updateCash", new java.lang.Integer (0));
    _methods.put ("createOperator", new java.lang.Integer (1));
    _methods.put ("createWallet", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // isimarket/model/servants/administrationservant/AdministrationServant/updateCash
       {
         String operatorLogin = in.read_string ();
         float newCash = in.read_float ();
         this.updateCash (operatorLogin, newCash);
         out = $rh.createReply();
         break;
       }

       case 1:  // isimarket/model/servants/administrationservant/AdministrationServant/createOperator
       {
         String operatorLogin = in.read_string ();
         String password = in.read_string ();
         float initalCash = in.read_float ();
         this.createOperator (operatorLogin, password, initalCash);
         out = $rh.createReply();
         break;
       }

       case 2:  // isimarket/model/servants/administrationservant/AdministrationServant/createWallet
       {
         float initalCash = in.read_float ();
         this.createWallet (initalCash);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:isimarket/model/servants/administrationservant/AdministrationServant:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _AdministrationServantImplBase
