package isimarket.servants.administrationservant;


/**
* isimarket/model/servants/administrationservant/AdministrationServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 24 mars 2008 12 h 24 CET
*/

public interface AdministrationServant extends AdministrationServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdministrationServant
