package isimarket.servants.administrationservant;


/**
* isimarket/model/servants/administrationservant/AdministrationServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 8 avril 2008 19 h 27 CEST
*/

public interface AdministrationServantOperations 
{
  void updateCash (String operatorLogin, float newCash);
  void createOperator (String operatorLogin, String password, float initalCash);
  void createWallet (float initalCash);
} // interface AdministrationServantOperations
