package isimarket.servants.administrationservant;


/**
* isimarket/model/servants/administrationservant/AdministrationServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 25 mars 2008 18 h 20 CET
*/

public interface AdministrationServantOperations 
{
  void updateCash (String operatorLogin, float newCash);
  void createOperator (String operatorLogin, String password);
  void createWallet (String operatorLogin, float initalCash);
} // interface AdministrationServantOperations
