package isimarket.servants.administrationservant;


/**
* isimarket/model/servants/administrationservant/AdministrationServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 12 mai 2008 16 h 16 CEST
*/

public interface AdministrationServant extends AdministrationServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdministrationServant
