package isimarket.model;


/**
* isimarket/model/WalletHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* mardi 8 avril 2008 19 h 22 CEST
*/

abstract public class WalletHelper
{
  private static String  _id = "IDL:isimarket/model/Wallet:1.0";

  public static void insert (org.omg.CORBA.Any a, isimarket.model.Wallet that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static isimarket.model.Wallet extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "walletId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[1] = new org.omg.CORBA.StructMember (
            "cash",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (isimarket.model.WalletHelper.id (), "Wallet", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static isimarket.model.Wallet read (org.omg.CORBA.portable.InputStream istream)
  {
    isimarket.model.Wallet value = new isimarket.model.Wallet ();
    value.walletId = istream.read_long ();
    value.cash = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, isimarket.model.Wallet value)
  {
    ostream.write_long (value.walletId);
    ostream.write_float (value.cash);
  }

}
