package isimarket.servants.eventservant;


/**
* isimarket/model/servants/eventservant/EventServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 13 mai 2008 19 h 01 CEST
*/

public interface EventServant extends EventServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EventServant
