package isimarket.servants.eventservant;

/**
* isimarket/model/servants/eventservant/EventServantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 12 mai 2008 16 h 16 CEST
*/

public final class EventServantHolder implements org.omg.CORBA.portable.Streamable
{
  public isimarket.servants.eventservant.EventServant value = null;

  public EventServantHolder ()
  {
  }

  public EventServantHolder (isimarket.servants.eventservant.EventServant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isimarket.servants.eventservant.EventServantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isimarket.servants.eventservant.EventServantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isimarket.servants.eventservant.EventServantHelper.type ();
  }

}
