package isimarket.servants.eventservant;


/**
* isimarket/model/servants/eventservant/EventServantHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 12 mai 2008 16 h 16 CEST
*/

abstract public class EventServantHelper
{
  private static String  _id = "IDL:isimarket/model/servants/eventservant/EventServant:1.0";

  public static void insert (org.omg.CORBA.Any a, isimarket.servants.eventservant.EventServant that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static isimarket.servants.eventservant.EventServant extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (isimarket.servants.eventservant.EventServantHelper.id (), "EventServant");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static isimarket.servants.eventservant.EventServant read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EventServantStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, isimarket.servants.eventservant.EventServant value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static isimarket.servants.eventservant.EventServant narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof isimarket.servants.eventservant.EventServant)
      return (isimarket.servants.eventservant.EventServant)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      isimarket.servants.eventservant._EventServantStub stub = new isimarket.servants.eventservant._EventServantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static isimarket.servants.eventservant.EventServant unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof isimarket.servants.eventservant.EventServant)
      return (isimarket.servants.eventservant.EventServant)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      isimarket.servants.eventservant._EventServantStub stub = new isimarket.servants.eventservant._EventServantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
