package isimarket.servants.eventservant;


/**
* isimarket/model/servants/eventservant/EventServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 21 avril 2008 12 h 28 CEST
*/

public interface EventServantOperations 
{
  void createEvent (String date, float price, String actionTypeCode);
  void deleteEvent (int eventId);
  isimarket.model.Event get (int eventId);
  isimarket.model.Event[] getEventListFromActionType (String actionTypeCode);
} // interface EventServantOperations
