package isimarket.servants.eventservant;


/**
* isimarket/model/servants/eventservant/EventServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 13 mai 2008 19 h 01 CEST
*/

public interface EventServantOperations 
{
  void createEvent (String date, float price, String actionTypeCode);
  void deleteEvent (int eventId);
  isimarket.model.Event get (int eventId);
  isimarket.model.Event[] getEventsForActionType (String actionTypeCode);
  void deleteEventsForActionType (String actionTypeCode);
} // interface EventServantOperations
