#include <model.idl>
module isimarket{
	module model{
		module servants{
			module administrationservant{
				interface AdministrationServant{
					void updateCash(in string operatorLogin, in  float newCash);
					void createOperator(in string operatorLogin, in string password);
					void createWallet(in string operatorLogin, in float initalCash);
				};
			};
			
			module walletservant{
				interface WalletServant{
					Wallet getWallet(in string operatorLogin, in string password);
					// ? float getCash(in long wallet_id);
					ActionList getActionListForWallet(in long id); 
				};
			};
			
			module webservant{
				interface WebServant{
					void createNewActionType(in ActionType newAcionType);
					void updateActionType(in float newPrice);
				};
			};
			
			module alarmservant{
				interface AlarmServant{
					
				};
			};
			
			module actionservant{
				interface ActionServant{
					ActionTypeList getActionTypeList();
					ActionList buyAction(in string actionTypeLabel, in long quantity);
					void sellAction(in string actionTypeLabel, in long quantity, in long actions_id);
					ActionType getActionType(in string label);
				};
			};
		};
	};
};