module market {
	module model {
		module wallet {
			struct Wallet{
			    float cash;

			    short operator_id;
			
				//public List<Action> actions = new ArrayList<Action>();
				//public List<Alarm> alarms = new ArrayList<Alarm>();
			};
		};
	};
};
