/*
 * MainFrame.java
 *
 * Created on 12 mars 2007, 17:29
 */

package gui;

import model.Bus;

import common.Constante;

import controler.ClientControler;

/**
 * 
 * @author garwind
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private static MainFrame mainFrame;

	public static MainFrame getInstance() {
		if (mainFrame == null)
			mainFrame = new MainFrame();
		return mainFrame;
	}

	/** Creates new form MainFrame */
	private MainFrame() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	@SuppressWarnings("deprecation")
	private void initComponents() {
		buttonsPanel = new javax.swing.JPanel();
		connectButton = new javax.swing.JButton();
		tabbedPane = new javax.swing.JTabbedPane();
		controlePanel = new javax.swing.JPanel();
		busTableScrollPane = new javax.swing.JScrollPane();
		busTable = new javax.swing.JTable();
		startBusButton = new javax.swing.JButton();
		breakBusButton = new javax.swing.JButton();
		accelerateBusButton = new javax.swing.JButton();
		decelerateBusButton = new javax.swing.JToggleButton();
		incidentBusButton = new javax.swing.JButton();
		busListLabel = new javax.swing.JLabel();
		creationPanel = new javax.swing.JPanel();
		creationPanel1 = new javax.swing.JPanel();
		busStopPanel = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		busStopTable = new javax.swing.JTable();
		busStopListLabel = new javax.swing.JLabel();
		createBusLabel = new javax.swing.JLabel();
		busIdInoutText = new javax.swing.JTextField();
		busLineLabel = new javax.swing.JLabel();
		busLinesComboBox = new javax.swing.JComboBox();
		creationPanel2 = new javax.swing.JPanel();
		createBusButton = new javax.swing.JButton();
		menuBar = new javax.swing.JMenuBar();
		applicationMenu = new javax.swing.JMenu();
		exitItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("ISI Bus Navigator");
		setName("ISI Bus Navigator");
		setResizable(false);
		connectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/resources/images/connect32x32.jpg")));
		connectButton.setText("Connect");
		connectButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				connectButtonActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout buttonsPanelLayout = new org.jdesktop.layout.GroupLayout(
				buttonsPanel);
		buttonsPanel.setLayout(buttonsPanelLayout);
		buttonsPanelLayout
				.setHorizontalGroup(buttonsPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								buttonsPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												connectButton,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												136,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(504, Short.MAX_VALUE)));
		buttonsPanelLayout
				.setVerticalGroup(buttonsPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								buttonsPanelLayout
										.createSequentialGroup()
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.add(
												connectButton,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												37,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		// busTable.setModel(new
		// BusTableModel(ClientControler.getInstance().getBus()));

		busTableScrollPane.setViewportView(busTable);

		startBusButton.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/resources/images/start.png")));
		startBusButton.setText(" Demarrer un Bus");
		startBusButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				startBusButtonActionPerformed(evt);
			}
		});

		breakBusButton.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/resources/images/stop.png")));
		breakBusButton.setText(" Accident sur un Bus");
		breakBusButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				breakBusButtonActionPerformed(evt);
			}
		});

		busListLabel.setText("Liste des bus :");

		accelerateBusButton.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/resources/images/accelerate.png")));
		accelerateBusButton.setText("Acc\u00e9lerer un Bus");
		accelerateBusButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						accelerateBusButtonActionPerformed(evt);
					}
				});

		decelerateBusButton.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/resources/images/decelerate.png")));
		decelerateBusButton.setText("D\u00e9celerer un Bus");
		decelerateBusButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						decelerateBusButtonActionPerformed(evt);
					}
				});

		incidentBusButton.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/resources/images/incident.png")));
		incidentBusButton.setText("Panne sur un Bus");
		incidentBusButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						incidentBusButtonActionPerformed(evt);
					}
				});

		org.jdesktop.layout.GroupLayout controlePanelLayout = new org.jdesktop.layout.GroupLayout(
				controlePanel);
		controlePanel.setLayout(controlePanelLayout);
		controlePanelLayout
				.setHorizontalGroup(controlePanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								controlePanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												controlePanelLayout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(busListLabel)
														.add(
																busTableScrollPane,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																381,
																Short.MAX_VALUE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												controlePanelLayout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																breakBusButton,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																236,
																Short.MAX_VALUE)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																startBusButton,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																236,
																Short.MAX_VALUE)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																incidentBusButton,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																236,
																Short.MAX_VALUE)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																accelerateBusButton,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																236,
																Short.MAX_VALUE)
														.add(
																decelerateBusButton,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																236,
																Short.MAX_VALUE))
										.addContainerGap()));
		controlePanelLayout
				.setVerticalGroup(controlePanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								controlePanelLayout
										.createSequentialGroup()
										.add(
												controlePanelLayout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																controlePanelLayout
																		.createSequentialGroup()
																		.add(
																				12,
																				12,
																				12)
																		.add(
																				busListLabel)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				startBusButton)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				breakBusButton,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				48,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				incidentBusButton,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				45,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				accelerateBusButton,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				49,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				decelerateBusButton,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				49,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																controlePanelLayout
																		.createSequentialGroup()
																		.add(
																				33,
																				33,
																				33)
																		.add(
																				busTableScrollPane,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				321,
																				Short.MAX_VALUE)))
										.add(12, 12, 12)));
		tabbedPane.addTab("Contr\u00f4le des Bus", controlePanel);

		jScrollPane1.setViewportView(busStopTable);

		busStopListLabel.setText("Liste des arr\u00e9ts :");

		org.jdesktop.layout.GroupLayout busStopPanelLayout = new org.jdesktop.layout.GroupLayout(
				busStopPanel);
		busStopPanel.setLayout(busStopPanelLayout);
		busStopPanelLayout
				.setHorizontalGroup(busStopPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								busStopPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												busStopPanelLayout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jScrollPane1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																623,
																Short.MAX_VALUE)
														.add(busStopListLabel))
										.addContainerGap()));
		busStopPanelLayout
				.setVerticalGroup(busStopPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								busStopPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.add(busStopListLabel)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												321, Short.MAX_VALUE)
										.addContainerGap()));
		tabbedPane.addTab("Informations des Arr\u00e9ts Bus", busStopPanel);

		createBusLabel.setText("Identifiant du bus : ");

		busLineLabel.setText("Liste des lignes de bus : ");

		busLinesComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "12", "24" }));

		org.jdesktop.layout.GroupLayout creationPanel1Layout = new org.jdesktop.layout.GroupLayout(
				creationPanel1);
		creationPanel1.setLayout(creationPanel1Layout);
		creationPanel1Layout
				.setHorizontalGroup(creationPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								creationPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												creationPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																creationPanel1Layout
																		.createSequentialGroup()
																		.add(
																				createBusLabel)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				busIdInoutText,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				33,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																creationPanel1Layout
																		.createSequentialGroup()
																		.add(
																				busLineLabel)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				busLinesComboBox,
																				0,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addContainerGap(
												145,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));
		creationPanel1Layout
				.setVerticalGroup(creationPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								creationPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												creationPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(createBusLabel)
														.add(
																busIdInoutText,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																19,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												creationPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(busLineLabel)
														.add(
																busLinesComboBox,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(42, Short.MAX_VALUE)));

		createBusButton.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/resources/images/add.png")));
		createBusButton.setText("Ajouter un Bus");
		createBusButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				createBusButtonActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout creationPanel2Layout = new org.jdesktop.layout.GroupLayout(
				creationPanel2);
		creationPanel2.setLayout(creationPanel2Layout);
		creationPanel2Layout
				.setHorizontalGroup(creationPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								creationPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												createBusButton,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												190, Short.MAX_VALUE)
										.addContainerGap()));
		creationPanel2Layout.setVerticalGroup(creationPanel2Layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(
						creationPanel2Layout.createSequentialGroup().add(21,
								21, 21).add(createBusButton).addContainerGap(
								32, Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout creationPanelLayout = new org.jdesktop.layout.GroupLayout(
				creationPanel);
		creationPanel.setLayout(creationPanelLayout);
		creationPanelLayout
				.setHorizontalGroup(creationPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								creationPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												creationPanel1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												creationPanel2,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addContainerGap()));
		creationPanelLayout
				.setVerticalGroup(creationPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								creationPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												creationPanelLayout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																creationPanelLayout
																		.createSequentialGroup()
																		.add(
																				creationPanel2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap())
														.add(
																creationPanelLayout
																		.createSequentialGroup()
																		.add(
																				creationPanel1,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addContainerGap(
																				249,
																				Short.MAX_VALUE)))));
		tabbedPane.addTab("Creation de Bus", creationPanel);

		applicationMenu.setLabel("Application");
		exitItem.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/resources/images/exit.gif")));
		exitItem.setText("Quitter");
		exitItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitItemActionPerformed(evt);
			}
		});

		applicationMenu.add(exitItem);

		menuBar.add(applicationMenu);

		setJMenuBar(menuBar);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap().add(
						layout.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING).add(
								buttonsPanel,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								tabbedPane,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								652, Short.MAX_VALUE)).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				layout.createSequentialGroup().addContainerGap().add(
						tabbedPane,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 393,
						Short.MAX_VALUE).addPreferredGap(
						org.jdesktop.layout.LayoutStyle.RELATED).add(
						buttonsPanel,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 686) / 2, (screenSize.height - 535) / 2,
				686, 535);
	}// </editor-fold>//GEN-END:initComponents

	private void decelerateBusButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_decelerateBusButtonActionPerformed
		int rownb = this.busTable.getSelectedRow();
		int busId = (Integer) ((BusTableModel) this.busTable.getModel())
				.getValueAt(rownb, 0);
		ClientControler.getInstance().sendCreateCommand(Constante.DEC_BUS,
				"" + busId, "null", 0, 0);

	}// GEN-LAST:event_decelerateBusButtonActionPerformed

	private void accelerateBusButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_accelerateBusButtonActionPerformed
		int rownb = this.busTable.getSelectedRow();
		int busId = (Integer) ((BusTableModel) this.busTable.getModel())
				.getValueAt(rownb, 0);
		ClientControler.getInstance().sendCreateCommand(Constante.ACC_BUS,
				"" + busId, "null", 0, 0);
	}// GEN-LAST:event_accelerateBusButtonActionPerformed

	private void incidentBusButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_incidentBusButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_incidentBusButtonActionPerformed

	private void breakBusButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_stopBusButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_breakBusButtonActionPerformed

	private void startBusButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_startBusButtonActionPerformed
		int rownb = this.busTable.getSelectedRow();
		int busId = (Integer) ((BusTableModel) this.busTable.getModel())
				.getValueAt(rownb, 0);
		ClientControler.getInstance().sendCreateCommand(Constante.START_BUS,
				"" + busId, "null", 0, 0);
		this.refreshBusTable();
	}// GEN-LAST:event_startBusButtonActionPerformed

	private void createBusButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createBusButtonActionPerformed
		ClientControler.getInstance().sendCreateCommand(Constante.BUS,
				this.busIdInoutText.getText().trim(),
				(String) this.busLinesComboBox.getSelectedItem(), 104, 37);
	}// GEN-LAST:event_createBusButtonActionPerformed

	private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_connectButtonActionPerformed
		ClientControler.getInstance().initialisation();
		this.connectButton.setEnabled(false);
		this.busTableModel = new BusTableModel(ClientControler.getInstance()
				.getBus());
		this.busStopTableModel = new InformationTableModel();
		busTable.setModel(busTableModel);
		busStopTable.setModel(busStopTableModel);
	}// GEN-LAST:event_connectButtonActionPerformed

	private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitItemActionPerformed
		System.out.println("exiting ...");
		System.exit(0);
	}// GEN-LAST:event_exitItemActionPerformed

	public void refreshBusTable() {
		this.busTableModel.refreshModel(ClientControler.getInstance().getBus());
		this.busTable.updateUI();
	}

	public void refreshInformation() {
		this.busStopTableModel.refreshModel();
		ClientControler.getInstance().getInformationsQueue().clear();
		this.busStopTable.updateUI();
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton accelerateBusButton;

	private javax.swing.JButton breakBusButton;

	private javax.swing.JToggleButton decelerateBusButton;

	private javax.swing.JButton incidentBusButton;

	private javax.swing.JMenu applicationMenu;

	private javax.swing.JTextField busIdInoutText;

	private javax.swing.JLabel busLineLabel;

	private javax.swing.JComboBox busLinesComboBox;

	private javax.swing.JLabel busListLabel;

	private javax.swing.JLabel busStopListLabel;

	private javax.swing.JPanel busStopPanel;

	private javax.swing.JTable busTable;

	private javax.swing.JScrollPane busTableScrollPane;

	private javax.swing.JPanel buttonsPanel;

	private javax.swing.JButton connectButton;

	private javax.swing.JPanel controlePanel;

	private javax.swing.JButton createBusButton;

	private javax.swing.JLabel createBusLabel;

	private javax.swing.JPanel creationPanel;

	private javax.swing.JPanel creationPanel1;

	private javax.swing.JPanel creationPanel2;

	private javax.swing.JMenuItem exitItem;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JTable busStopTable;

	private javax.swing.JMenuBar menuBar;

	private javax.swing.JButton startBusButton;

	private javax.swing.JTabbedPane tabbedPane;

	private BusTableModel busTableModel;

	private InformationTableModel busStopTableModel;
	// End of variables declaration//GEN-END:variables

}
