package isimarket.servants.walletservant.WalletServantPackage;


/**
* isimarket/model/servants/walletservant/WalletServantPackage/UnknownOperatorException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 13 mai 2008 19 h 01 CEST
*/

public final class UnknownOperatorException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public UnknownOperatorException ()
  {
    super(UnknownOperatorExceptionHelper.id());
  } // ctor

  public UnknownOperatorException (String _reason)
  {
    super(UnknownOperatorExceptionHelper.id());
    reason = _reason;
  } // ctor


  public UnknownOperatorException (String $reason, String _reason)
  {
    super(UnknownOperatorExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class UnknownOperatorException
