package isimarket.servants.walletservant;


/**
* isimarket/model/servants/walletservant/WalletServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* dimanche 4 mai 2008 19 h 59 CEST
*/

public interface WalletServant extends WalletServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WalletServant
