package isimarket.model;


/**
* isimarket/model/ActionTypeListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* lundi 31 mars 2008 16 h 30 CEST
*/

public final class ActionTypeListHolder implements org.omg.CORBA.portable.Streamable
{
  public isimarket.model.ActionType value[] = null;

  public ActionTypeListHolder ()
  {
  }

  public ActionTypeListHolder (isimarket.model.ActionType[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isimarket.model.ActionTypeListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isimarket.model.ActionTypeListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isimarket.model.ActionTypeListHelper.type ();
  }

}
