package isimarket.oldservants.alarmservant;

/**
* isimarket/model/servants/alarmservant/AlarmServantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* dimanche 30 mars 2008 16 h 51 CEST
*/

public final class AlarmServantHolder implements org.omg.CORBA.portable.Streamable
{
  public isimarket.oldservants.alarmservant.AlarmServant value = null;

  public AlarmServantHolder ()
  {
  }

  public AlarmServantHolder (isimarket.oldservants.alarmservant.AlarmServant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isimarket.oldservants.alarmservant.AlarmServantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isimarket.oldservants.alarmservant.AlarmServantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isimarket.oldservants.alarmservant.AlarmServantHelper.type ();
  }

}
