package isimarket.servants.walletservant.WalletServantPackage;

/**
* isimarket/model/servants/walletservant/WalletServantPackage/NotEnoughCashExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* dimanche 4 mai 2008 19 h 59 CEST
*/

public final class NotEnoughCashExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public isimarket.servants.walletservant.WalletServantPackage.NotEnoughCashException value = null;

  public NotEnoughCashExceptionHolder ()
  {
  }

  public NotEnoughCashExceptionHolder (isimarket.servants.walletservant.WalletServantPackage.NotEnoughCashException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isimarket.servants.walletservant.WalletServantPackage.NotEnoughCashExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isimarket.servants.walletservant.WalletServantPackage.NotEnoughCashExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isimarket.servants.walletservant.WalletServantPackage.NotEnoughCashExceptionHelper.type ();
  }

}
