package isimarket.servants.administrationservant;


/**
* isimarket/model/servants/administrationservant/AdministrationServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 1 avril 2008 18 h 10 CEST
*/

public interface AdministrationServantOperations 
{
  void updateCash (String operatorLogin, float newCash);
  void createOperator (isimarket.model.Operator _operator);
  void createWallet (float initalCash);
} // interface AdministrationServantOperations
