package isimarket.servants;


/**
* isimarket/model/servants/TestInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 24 mars 2008 11 h 43 CET
*/

abstract public class TestInterfaceHelper
{
  private static String  _id = "IDL:isimarket/model/servants/TestInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, isimarket.servants.TestInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static isimarket.servants.TestInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (isimarket.servants.TestInterfaceHelper.id (), "TestInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static isimarket.servants.TestInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TestInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, isimarket.servants.TestInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static isimarket.servants.TestInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof isimarket.servants.TestInterface)
      return (isimarket.servants.TestInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      isimarket.servants._TestInterfaceStub stub = new isimarket.servants._TestInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static isimarket.servants.TestInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof isimarket.servants.TestInterface)
      return (isimarket.servants.TestInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      isimarket.servants._TestInterfaceStub stub = new isimarket.servants._TestInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
