package isimarket.servants;

/**
* isimarket/model/servants/TestInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 24 mars 2008 11 h 43 CET
*/

public final class TestInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public isimarket.servants.TestInterface value = null;

  public TestInterfaceHolder ()
  {
  }

  public TestInterfaceHolder (isimarket.servants.TestInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isimarket.servants.TestInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isimarket.servants.TestInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isimarket.servants.TestInterfaceHelper.type ();
  }

}
