package isimarket.servants;


/**
* isimarket/model/servants/TestInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 24 mars 2008 11 h 43 CET
*/

public interface TestInterfaceOperations 
{
  isimarket.model.Wallet getOperatorWallet (String operatorName);
} // interface TestInterfaceOperations
