package isimarket.servants.administrationservant;


/**
* isimarket/model/servants/administrationservant/AdministrationServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 20 mai 2008 17 h 50 CEST
*/

public interface AdministrationServantOperations 
{
  void updateCash (String login, float newCash);
  void createOperator (String login, String password, float initalCash);
  void createWallet (float initalCash);
  void deleteOperator (String login);
} // interface AdministrationServantOperations
