package isimarket.model;


/**
* isimarket/model/OperatorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* lundi 31 mars 2008 16 h 30 CEST
*/

abstract public class OperatorHelper
{
  private static String  _id = "IDL:isimarket/model/Operator/Operator:1.0";

  public static void insert (org.omg.CORBA.Any a, isimarket.model.Operator that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static isimarket.model.Operator extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "login",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "password",
            _tcOf_members0,
            null);
          _tcOf_members0 = isimarket.model.WalletHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "wallet",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (isimarket.model.OperatorHelper.id (), "Operator", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static isimarket.model.Operator read (org.omg.CORBA.portable.InputStream istream)
  {
    isimarket.model.Operator value = new isimarket.model.Operator ();
    value.login = istream.read_string ();
    value.password = istream.read_string ();
    value.wallet = isimarket.model.WalletHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, isimarket.model.Operator value)
  {
    ostream.write_string (value.login);
    ostream.write_string (value.password);
    isimarket.model.WalletHelper.write (ostream, value.wallet);
  }

}
