package isimarket.servants.actiontypeservant;


/**
* isimarket/model/servants/actiontypeservant/ActionTypeServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* dimanche 30 mars 2008 16 h 51 CEST
*/

public interface ActionTypeServant extends ActionTypeServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ActionTypeServant
