package isimarket.servants.walletservant;


/**
* isimarket/model/servants/walletservant/_WalletServantImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 25 mars 2008 18 h 20 CET
*/

public abstract class _WalletServantImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements isimarket.servants.walletservant.WalletServant, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _WalletServantImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getWallet", new java.lang.Integer (0));
    _methods.put ("getActionListForWallet", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // isimarket/model/servants/walletservant/WalletServant/getWallet
       {
         String operatorLogin = in.read_string ();
         String password = in.read_string ();
         isimarket.model.Wallet $result = null;
         $result = this.getWallet (operatorLogin, password);
         out = $rh.createReply();
         isimarket.model.WalletHelper.write (out, $result);
         break;
       }


  // ? float getCash(in long wallet_id);
       case 1:  // isimarket/model/servants/walletservant/WalletServant/getActionListForWallet
       {
         int id = in.read_long ();
         isimarket.model.Action $result[] = null;
         $result = this.getActionListForWallet (id);
         out = $rh.createReply();
         isimarket.model.ActionListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:isimarket/model/servants/walletservant/WalletServant:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _WalletServantImplBase
