package isimarket.servants.walletservant;


/**
* isimarket/model/servants/walletservant/WalletServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* samedi 29 mars 2008 11 h 45 CET
*/

public interface WalletServantOperations 
{
  isimarket.model.Wallet getWallet (String operatorLogin, String password);
  isimarket.model.WalletAction[] getActionListForWallet (int walletId);
  isimarket.model.WalletAction getWalletAction (int walletId, int walletActionId);
  isimarket.model.WalletAction buyAction (String actionTypeCode, int walletId, int quantity);
  void sellAction (String actionTypeCode, int quantity, int walletActionId);
} // interface WalletServantOperations
