package isimarket.servants.walletservant;


/**
* isimarket/model/servants/walletservant/WalletServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* samedi 29 mars 2008 11 h 45 CET
*/

public interface WalletServant extends WalletServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WalletServant
