package isimarket.servants.walletservant;


/**
* isimarket/model/servants/walletservant/WalletServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 25 mars 2008 18 h 20 CET
*/

public interface WalletServantOperations 
{
  isimarket.model.Wallet getWallet (String operatorLogin, String password);

  // ? float getCash(in long wallet_id);
  isimarket.model.Action[] getActionListForWallet (int id);
} // interface WalletServantOperations
