package isimarket.model;


/**
* isimarket/model/Alarm.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* mardi 20 mai 2008 18 h 00 CEST
*/

public final class Alarm implements org.omg.CORBA.portable.IDLEntity
{
  public int alarmId = (int)0;
  public String name = null;
  public float value = (float)0;
  public isimarket.model.AlarmType type = null;
  public isimarket.model.ActionType actionType = null;
  public isimarket.model.Wallet wallet = null;

  public Alarm ()
  {
  } // ctor

  public Alarm (int _alarmId, String _name, float _value, isimarket.model.AlarmType _type, isimarket.model.ActionType _actionType, isimarket.model.Wallet _wallet)
  {
    alarmId = _alarmId;
    name = _name;
    value = _value;
    type = _type;
    actionType = _actionType;
    wallet = _wallet;
  } // ctor

} // class Alarm
