module isimarket{
	module model{
		struct Wallet{
			long walletId;
		    float cash;
		};
		
		struct ActionType{
		    string code;
		    string label;
		    string introductionDate;
		    float introductionPrice;
		    long quantity;
		    float currentPrice;
		};
		
		typedef sequence<ActionType> ActionTypeList;
		
		struct AlarmType{
			long alarmTypeId;
			string label;
		};
		
		typedef sequence<AlarmType> AlarmTypeList;
		
		struct Action{
			long actionId;
		    float buyPrice;
		    string buyDate;
		    long quantity;
		    ActionType actiontype;
		    Wallet wallet;
		};
		
		struct Event{
			long eventId;
		    float price;
		    string date;
		    ActionType actiontype;
		};
		
		typedef sequence<Event> EventList;
		
		struct Alarm{
		    long alarmId;
		    string name;
		    AlarmType type;
		    ActionType actionType;
		    Wallet wallet;
		};
		
		typedef sequence<Action> ActionList;
		typedef sequence<Alarm> AlarmList;
		
		struct Administrator{
		    string login;
		    string password;
		};
		
		struct Operator {
			string login;
			string password;
			Wallet wallet;
		};
	};
};