package isimarket.servants.alarmservant;


/**
* isimarket/model/servants/alarmservant/AlarmServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 12 mai 2008 16 h 00 CEST
*/

public interface AlarmServant extends AlarmServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AlarmServant
