package isimarket.servants.alarmservant;


/**
* isimarket/model/servants/alarmservant/AlarmServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* lundi 12 mai 2008 16 h 00 CEST
*/

public interface AlarmServantOperations 
{
  isimarket.model.AlarmType[] getAlarmTypeList ();
  isimarket.model.AlarmType getAlarmType (int alarmTypeId);
  void createAlarmType (String label);
  void deleteAlarmType (int alarmTypeId);
  isimarket.model.Alarm[] getAlarmListFromWallet (int walletId);
  isimarket.model.Alarm getAlarm (int alarmId);
  isimarket.model.Alarm createAlarm (String name, int walletId, int alarmTypeId, String actionTypeCode);
  void deleteAlarm (int alarmId);
} // interface AlarmServantOperations
