package market.model;


/**
* market/model/ActionListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 23 mars 2008 11 h 38 CET
*/

public final class ActionListHolder implements org.omg.CORBA.portable.Streamable
{
  public market.model.Action value[] = null;

  public ActionListHolder ()
  {
  }

  public ActionListHolder (market.model.Action[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = market.model.ActionListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    market.model.ActionListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return market.model.ActionListHelper.type ();
  }

}
