package market.model;

/**
* market/model/AdministratorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 23 mars 2008 11 h 38 CET
*/

public final class AdministratorHolder implements org.omg.CORBA.portable.Streamable
{
  public market.model.Administrator value = null;

  public AdministratorHolder ()
  {
  }

  public AdministratorHolder (market.model.Administrator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = market.model.AdministratorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    market.model.AdministratorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return market.model.AdministratorHelper.type ();
  }

}
