package market.model;

/**
* market/model/AlarmHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 23 mars 2008 11 h 38 CET
*/

public final class AlarmHolder implements org.omg.CORBA.portable.Streamable
{
  public market.model.Alarm value = null;

  public AlarmHolder ()
  {
  }

  public AlarmHolder (market.model.Alarm initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = market.model.AlarmHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    market.model.AlarmHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return market.model.AlarmHelper.type ();
  }

}
