package market.model;


/**
* market/model/Alarm.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 23 mars 2008 11 h 38 CET
*/

public final class Alarm implements org.omg.CORBA.portable.IDLEntity
{
  public int alarm_id = (int)0;
  public String name = null;

  //Wallet wallet;
  public market.model.AlarmType type = null;
  public market.model.ActionType actionType = null;

  public Alarm ()
  {
  } // ctor

  public Alarm (int _alarm_id, String _name, market.model.AlarmType _type, market.model.ActionType _actionType)
  {
    alarm_id = _alarm_id;
    name = _name;
    type = _type;
    actionType = _actionType;
  } // ctor

} // class Alarm
