package market.model;


/**
* market/model/AlarmListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 23 mars 2008 11 h 38 CET
*/

abstract public class AlarmListHelper
{
  private static String  _id = "IDL:market/model/AlarmList:1.0";

  public static void insert (org.omg.CORBA.Any a, market.model.Alarm[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static market.model.Alarm[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = market.model.AlarmHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (market.model.AlarmListHelper.id (), "AlarmList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static market.model.Alarm[] read (org.omg.CORBA.portable.InputStream istream)
  {
    market.model.Alarm value[] = null;
    int _len0 = istream.read_long ();
    value = new market.model.Alarm[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = market.model.AlarmHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, market.model.Alarm[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      market.model.AlarmHelper.write (ostream, value[_i0]);
  }

}
