package market.model;

/**
* market/model/OperatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 23 mars 2008 11 h 38 CET
*/

public final class OperatorHolder implements org.omg.CORBA.portable.Streamable
{
  public market.model.Operator value = null;

  public OperatorHolder ()
  {
  }

  public OperatorHolder (market.model.Operator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = market.model.OperatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    market.model.OperatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return market.model.OperatorHelper.type ();
  }

}
