package market.model;


/**
* market/model/Operator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 23 mars 2008 11 h 38 CET
*/

public final class Operator implements org.omg.CORBA.portable.IDLEntity
{
  public String login = null;
  public String password = null;
  public market.model.Wallet wallet = null;

  public Operator ()
  {
  } // ctor

  public Operator (String _login, String _password, market.model.Wallet _wallet)
  {
    login = _login;
    password = _password;
    wallet = _wallet;
  } // ctor

} // class Operator
