package market.model;


/**
* market/model/Wallet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 23 mars 2008 11 h 38 CET
*/

public final class Wallet implements org.omg.CORBA.portable.IDLEntity
{
  public int wallet_id = (int)0;
  public float cash = (float)0;
  public market.model.Action actions[] = null;

  //public List<Action> actions = new ArrayList<Action>();
  public market.model.Alarm alarms[] = null;

  public Wallet ()
  {
  } // ctor

  public Wallet (int _wallet_id, float _cash, market.model.Action[] _actions, market.model.Alarm[] _alarms)
  {
    wallet_id = _wallet_id;
    cash = _cash;
    actions = _actions;
    alarms = _alarms;
  } // ctor

} // class Wallet
