package market.model;


/**
* market/model/WalletHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from model.idl
* dimanche 23 mars 2008 11 h 38 CET
*/

abstract public class WalletHelper
{
  private static String  _id = "IDL:market/model/Wallet/Wallet:1.0";

  public static void insert (org.omg.CORBA.Any a, market.model.Wallet that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static market.model.Wallet extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "wallet_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[1] = new org.omg.CORBA.StructMember (
            "cash",
            _tcOf_members0,
            null);
          _tcOf_members0 = market.model.ActionHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (market.model.ActionListHelper.id (), "ActionList", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "actions",
            _tcOf_members0,
            null);
          _tcOf_members0 = market.model.AlarmHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (market.model.AlarmListHelper.id (), "AlarmList", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "alarms",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (market.model.WalletHelper.id (), "Wallet", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static market.model.Wallet read (org.omg.CORBA.portable.InputStream istream)
  {
    market.model.Wallet value = new market.model.Wallet ();
    value.wallet_id = istream.read_long ();
    value.cash = istream.read_float ();
    value.actions = market.model.ActionListHelper.read (istream);
    value.alarms = market.model.AlarmListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, market.model.Wallet value)
  {
    ostream.write_long (value.wallet_id);
    ostream.write_float (value.cash);
    market.model.ActionListHelper.write (ostream, value.actions);
    market.model.AlarmListHelper.write (ostream, value.alarms);
  }

}
