package isimarket.servants.administrationservant;


/**
* isimarket/model/servants/administrationservant/AdministrationServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from services.idl
* mardi 13 mai 2008 19 h 01 CEST
*/

public interface AdministrationServant extends AdministrationServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdministrationServant
